name: Build and Push 📦

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Execute test and generate coverage report
        run: |
          chmod +x ./mvnw 
          ./mvnw test verify jacoco:report
        
      - name: Run Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: target/site/jacoco/jacoco.xml
          
      - name: Build package with Maven (skip tests)
        run: ./mvnw clean package -DskipTests

      - name: Set execute permissions for build script
        run: chmod +x build-image.sh

      - name: Run build script
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: ./build-image.sh
